[package]
name = "yuvxyb"
description = "Direct conversions between YUV (YCbCr) and XYB colorspaces"
version = "0.1.0"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/yuvxyb"
homepage = "https://github.com/rust-av/yuvxyb"
repository = "https://github.com/rust-av/yuvxyb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
av-data = "0.4.1"
debug_unreachable = { package = "new_debug_unreachable", version = "1.0.4" }
image = { version = "0.24.4", default-features = false, features = [
    "png",
], optional = true }
log = "0.4.17"
nalgebra = "0.31.1"
num-traits = "0.2.15"
once_cell = "1.15.0"
paste = "1.0.9"
v_frame = "0.3.0"

[dev-dependencies]
criterion = "0.4.0"
interpolate_name = "0.2.3"
pxm = "0.1.0"
rand = "0.8.5"

[[bench]]
name = "benches"
harness = false

[features]
# Intended for debugging, will output grayscale images of each plane
dump = ["image"]
